# Generated by Django 5.1.1 on 2025-05-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('action', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='local', max_length=100)),
                ('section_id', models.TextField()),
                ('section_uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('userId', models.IntegerField()),
                ('rank', models.TextField(blank=True, null=True)),
                ('isHidden', models.TextField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200, unique=True)),
                ('number', models.CharField(max_length=255)),
                ('currentDate', models.TextField()),
                ('reportDate', models.TextField()),
                ('documentOutDetails', models.TextField()),
                ('requestedInformation', models.TextField(verbose_name='المعلومات المطلوبة')),
                ('conclusion', models.TextField()),
                ('userId', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
