# Generated by Django 5.1.1 on 2025-05-17 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newforenapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committeemember',
            old_name='action',
            new_name='position',
        ),
    ]
