# Generated by Django 5.1.1 on 2025-05-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newforenapp', '0002_rename_action_committeemember_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='incidents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
